# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

monitor = eDP-1, 1920x1200@60, 0x0, 1
monitor = HDMI-A-2, 1920x1080@60, 1920x0, 1
monitor = DP-2, 1920x1080@60, 3840x0, 1

$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = fuzzel

#keybinds
bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod SHIFT, right, movewindow, mon:r
bind = $mainMod SHIFT, left, movewindow, mon:l
